### PR TITLE
Update for 3.1.2

### PR DESCRIPTION
**Pull request by ksunden**

### CODE REVIEW

**Comment by ksunden** [comment]
@conda-forge/core 
Linter appears to be failing incorrectly, as the maintainers list did not change for this version.

Note, this also happened in #19 and #20, previous attempts by myself and the rever bot, respectively to update 

Cursory look at other feedstocks seem to be experiencing similar issues with the linter.

**Comment by CJ-Wright** [comment]
We're working on it https://github.com/conda-forge/conda-smithy/pull/877

**Comment by ksunden** [comment]
@conda-forge-admin, please lint

**Comment by ksunden** [comment]
@conda-forge-admin, please lint

**Comment by ksunden** [comment]
@conda-forge-admin, please lint

**Pull request merged**
